### ISSUE TITLE
域名似乎失效了

### ISSUE THREAD

**Issue by rchee** [easychen/gpt-bat#5]
https://gpt.level06.com/ 网站提示 DNS_PROBE_FINISHED_NXDOMAIN
<img width="1083" alt="image" src="https://github.com/easychen/gpt-bat/assets/5948724/76973459-f5bf-4f08-b477-fc2a82bf3c98">

**Comment by easychen** [comment]
用这个  [r.ftqq.com/gpt-bat/](http://r.ftqq.com/gpt-bat/)
